#Ali, Aboelela 22398556

# Questions Answers 
**Part A:

**1_Define the problem. What is the input? What is the output?**

The problem is to predict the product ratings of Wish.com products based on other features of the products. The input is the various features of the products such as product type, description, price, and image, among others. The output is the predicted product rating, which is in categories from 1 to 5. The goal is to estimate how likely people will like a product and understand the conditions under which a product will be highly rated.

2_What data mining function is required?

The data mining function required is classification or prediction since the goal is to predict the product rating based on other features of the product.

**3_What could be the challenges?**

The challenges could include dealing with noisy data, missing values, and irrelevant or unnecessary features. Also, the features included in the dataset may not be sufficient to accurately predict the product rating, which may require additional data sources or feature engineering.

**4_What is the impact?**

The impact of accurately predicting the product rating is that it can help businesses understand their customer base and tailor their products to meet customer preferences. It can also help businesses identify the features that are most important to customers, which can inform product development and marketing strategies.

**5_What is an ideal solution?**

My expermint SVM is the Ideal model for this problem.
but in general An ideal solution would be to develop a machine learning model that accurately predicts the product rating based on the available features, while also being able to handle missing or noisy data. The model should also be easily interpretable, so that businesses can understand the factors that are most important for predicting product ratings. Additionally, the model should be regularly updated with new data to ensure its accuracy over time.

** Part B:

**1_**Data mining is a misnomer because the term implies that mining for data is the primary objective, when in reality, the objective is to extract useful knowledge from data. Another preferred name is Knowledge Discovery in Databases (KDD).

**2_**The general knowledge discovery process involves several steps including data selection, data pre-processing, data transformation, data mining, pattern evaluation, and knowledge representation. This process involves identifying patterns and relationships within the data to gain insights and make predictions.

A data engineer is responsible for designing, building, and maintaining the infrastructure that supports the storing, processing, and analysis of data. A data scientist or AI engineer is responsible for developing and applying statistical and machine learning techniques to extract insights and make predictions from data.

**3_**In data mining, prediction involves using historical data to make a prediction about future events or outcomes. Categorization involves grouping data into predetermined categories based on similarities or differences.

**4_**Data science and machine learning can be a bad idea in the context of information security because they can be used for malicious purposes such as hacking, phishing, and identity theft. These technologies can also be used to analyze large amounts of data from various sources to identify vulnerabilities or weaknesses in security systems.

**5_**The CIA principle refers to the three main goals of information security: confidentiality, integrity, and availability. Confidentiality ensures that data is accessed only by authorized individuals, integrity ensures that data is accurate and consistent, and availability ensures that data is accessible to authorized individuals when needed. To assess the security and privacy aspects of an AI system or pipeline, we can evaluate how well it protects these three aspects of information security.

**The problem at hand** 

is to build a model to predict the rating of products on the Wish E-commerce platform using input features such as price, retail price, product size, and product color. The objective is to answer questions such as what the top-selling products are, which features are most important in predicting product success, and what the expected product rating will be before listing it on the site. However, the dataset is unclean, requiring significant preprocessing.

Another challenge is that the dataset is imbalanced, with a large number of products rated 4 and only a few rated 2. The impact of solving this problem is that businesses can make informed decisions about which products to market and how to tailor them to customer preferences. Additionally, understanding the factors that drive product success can inform product development and marketing strategies.

**The data mining function** 

required is classification or prediction, as the goal is to predict the product rating based on input features.

**The data mining**

 process utilizes classification and prediction techniques to transform raw data into a format that can be analyzed. To ensure that the data is suitable for analysis, it undergoes several important steps.

The first step is data processing, where irrelevant and unnecessary features are identified and removed, null values are checked and replaced, and new features are created from existing ones if necessary. Additionally, categorical variables are cleaned in this step.

The second step involves converting categorical and string columns into numerical columns so that they can be used with machine learning models.

Finally, the best model is selected by building and testing various models on the pre-processed data. This ensures that the most accurate and effective model is used for data analysis.

In [183]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
from sklearn.model_selection import train_test_split
import re
import math

In [184]:
df= pd.read_csv('train_new.csv')
df.head()

,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,badges_count,badge_local_product,badge_product_quality,...,merchant_name,merchant_info_subtitle,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,theme,crawl_month,id
0,8.00,7,EUR,10000,1,4.0,1670,0,0,0,...,keepahorse,"88 % avis positifs (66,644 notes)",66644,4.137582,577fb2b368116418674befd9,1,https://s3-us-west-1.amazonaws.com/sweeper-pro...,summer,2020-08,272
1,8.00,7,EUR,1000,0,4.0,843,1,1,0,...,上海铭启电气科技有限公司,"91 % avis positifs (25,752 notes)",25752,4.256873,566a3ef17233ff2686443082,0,NaN,summer,2020-08,1515
2,6.00,34,EUR,100,0,4.0,10,0,0,0,...,zhaodongmei,"83 % avis positifs (3,897 notes)",3897,3.928920,5aacd6c1ccf0c83e5a6f3de0,0,NaN,summer,2020-08,940
3,4.67,4,EUR,100,1,3.0,82,0,0,0,...,pookie0331,"87 % avis positifs (7,497 notes)",7497,4.079365,583141fbfef4094e51453d9b,0,NaN,summer,2020-08,309
4,8.00,11,EUR,1000,0,4.0,127,0,0,0,...,shitongyi12683626,91 % avis positifs (173 notes),173,4.306358,5d3bc9f8e13a7e654424a4cb,0,NaN,summer,2020-08,226

In [185]:
df2= df.drop(columns=['theme','urgency_text','merchant_title','merchant_info_subtitle','currency_buyer','merchant_name','merchant_id','merchant_profile_picture','crawl_month','tags'])
df2.set_index('id',inplace=True)
df2.head()

,price,retail_price,units_sold,uses_ad_boosts,rating,rating_count,badges_count,badge_local_product,badge_product_quality,badge_fast_shipping,...,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,origin_country,merchant_rating_count,merchant_rating,merchant_has_profile_picture
id,,,,,,,,,,,,,,,,,,,,,
272,8.00,7,10000,1,4.0,1670,0,0,0,0,...,Livraison standard,3,0,30,50,NaN,CN,66644,4.137582,1
1515,8.00,7,1000,0,4.0,843,1,1,0,0,...,Livraison standard,3,0,37,50,NaN,CN,25752,4.256873,0
940,6.00,34,100,0,4.0,10,0,0,0,0,...,Livraison standard,2,0,41,50,NaN,CN,3897,3.928920,0
309,4.67,4,100,1,3.0,82,0,0,0,0,...,Livraison standard,1,0,25,50,NaN,CN,7497,4.079365,0
226,8.00,11,1000,0,4.0,127,0,0,0,0,...,Livraison standard,3,0,15,50,1.0,CN,173,4.306358,0

In [186]:
df2.isnull().sum()

price                             0
retail_price                      0
units_sold                        0
uses_ad_boosts                    0
rating                            0
rating_count                      0
badges_count                      0
badge_local_product               0
badge_product_quality             0
badge_fast_shipping               0
product_color                    29
product_variation_size_id        12
product_variation_inventory       0
shipping_option_name              0
shipping_option_price             0
shipping_is_express               0
countries_shipped_to              0
inventory_total                   0
has_urgency_banner              745
origin_country                   12
merchant_rating_count             0
merchant_rating                   0
merchant_has_profile_picture      0
dtype: int64

we see that there is some columns with missing values

#Normalize numerical columns

In [187]:
#min_max_scaler constructor
min_max_scaler = MinMaxScaler()
#extract integer columns
myCols = df2.select_dtypes(include='int64').columns
#normlize integer columns
df2[myCols] = min_max_scaler.fit_transform(df2[myCols])
#normalize float columns
df2[['price','merchant_rating']] = min_max_scaler.fit_transform(df2[['price','merchant_rating']])

**rating column has value 6**

In [188]:
print(df2["rating"].value_counts())
mode = df2[df2["rating"]!="?"]["rating"].mode()[0]
df2['rating'] = df2['rating'].replace(6.0, mode)
print(df2["rating"].value_counts())

4.0    774
5.0    170
3.0    135
2.0     12
1.0      2
6.0      1
Name: rating, dtype: int64
4.0    775
5.0    170
3.0    135
2.0     12
1.0      2
Name: rating, dtype: int64

#size column has too many null and similar values

In [189]:
"""helper functions to clean data"""
def clean_product_size(cell):
    
    #replace null values with "ANOTHER_SIZE"
    if not isinstance(cell,str) and math.isnan(cell):
        return "ANOTHER_SIZE"

    #set some regex patterns    
    pattern = re.compile(r'(\bL\b|(?<=[^MF])L|\bX+S|S\b|\bS\b|\dXS|\bM\b|\d?X+L)')
    match = re.search(pattern,cell)
    #if value doesn't match the pattern don't do anything.
    if match is not None:
        cell = match[0]

    #if value has more than X replace the value the number of X's       
    if cell.count('X') > 1 and (cell.endswith('XS') or cell.endswith('XL')):
        cell = f"{cell.count('X')}X{cell[-1]}"
    return cell  

def replace_less_values(col,value_to_be_replaced):
    #extract values with count 2 or less than 2
    bool_lst = [df2[col].value_counts() <= 2]
    lst = list(df2[col].value_counts().index[tuple(bool_lst)])
    #replace them with value of my choice
    df2[col].replace(dict.fromkeys(lst, value_to_be_replaced),inplace=True)    


    
#Count of product_variation_size_id before the cleaning.
print(df2['product_variation_size_id'].value_counts())
df2['product_variation_size_id'] = df2['product_variation_size_id'].str.upper()
df2.product_variation_size_id = df2.product_variation_size_id.apply(clean_product_size)
replace_less_values('product_variation_size_id','ANOTHER_SIZE')
#Count of product_variation_size_id after the cleaning.
df2.product_variation_size_id.value_counts()

S           444
XS          248
M           135
XXS          76
L            29
           ...
pants-S       1
XXXXL         1
SIZE-XXS      1
1pc           1
H01           1
Name: product_variation_size_id, Length: 83, dtype: int64

S               488
XS              258
M               141
2XS              82
ANOTHER_SIZE     47
L                32
2XL              14
XL               13
4XL               7
3XS               5
5XL               4
10 ML             3
Name: product_variation_size_id, dtype: int64

#Convert categorical columns to Numerical

In [190]:
#identify all categorical variables
cat_columns = df2.select_dtypes(['object']).columns

#convert all categorical variables to numeric
df2[cat_columns] = df2[cat_columns].apply(lambda x: pd.factorize(x)[0])

In [191]:
df2.head()

,price,retail_price,units_sold,uses_ad_boosts,rating,rating_count,badges_count,badge_local_product,badge_product_quality,badge_fast_shipping,...,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,origin_country,merchant_rating_count,merchant_rating,merchant_has_profile_picture
id,,,,,,,,,,,,,,,,,,,,,
272,0.145833,0.020,0.099991,1.0,4.0,0.080505,0.000000,0.0,0.0,0.0,...,0,0.181818,0.0,0.166667,1.0,NaN,0,0.030642,0.731146,1.0
1515,0.145833,0.020,0.009990,0.0,4.0,0.040638,0.333333,1.0,0.0,0.0,...,0,0.181818,0.0,0.219697,1.0,NaN,0,0.011839,0.804047,0.0
940,0.104167,0.128,0.000990,0.0,4.0,0.000482,0.000000,0.0,0.0,0.0,...,0,0.090909,0.0,0.250000,1.0,NaN,0,0.001790,0.603628,0.0
309,0.076458,0.008,0.000990,1.0,3.0,0.003953,0.000000,0.0,0.0,0.0,...,0,0.000000,0.0,0.128788,1.0,NaN,0,0.003445,0.695569,0.0
226,0.145833,0.036,0.009990,0.0,4.0,0.006122,0.000000,0.0,0.0,0.0,...,0,0.181818,0.0,0.053030,1.0,1.0,0,0.000078,0.834288,0.0

In [192]:
df2.head()

,price,retail_price,units_sold,uses_ad_boosts,rating,rating_count,badges_count,badge_local_product,badge_product_quality,badge_fast_shipping,...,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,origin_country,merchant_rating_count,merchant_rating,merchant_has_profile_picture
id,,,,,,,,,,,,,,,,,,,,,
272,0.145833,0.020,0.099991,1.0,4.0,0.080505,0.000000,0.0,0.0,0.0,...,0,0.181818,0.0,0.166667,1.0,NaN,0,0.030642,0.731146,1.0
1515,0.145833,0.020,0.009990,0.0,4.0,0.040638,0.333333,1.0,0.0,0.0,...,0,0.181818,0.0,0.219697,1.0,NaN,0,0.011839,0.804047,0.0
940,0.104167,0.128,0.000990,0.0,4.0,0.000482,0.000000,0.0,0.0,0.0,...,0,0.090909,0.0,0.250000,1.0,NaN,0,0.001790,0.603628,0.0
309,0.076458,0.008,0.000990,1.0,3.0,0.003953,0.000000,0.0,0.0,0.0,...,0,0.000000,0.0,0.128788,1.0,NaN,0,0.003445,0.695569,0.0
226,0.145833,0.036,0.009990,0.0,4.0,0.006122,0.000000,0.0,0.0,0.0,...,0,0.181818,0.0,0.053030,1.0,1.0,0,0.000078,0.834288,0.0

#Data cleaning
**1-Product color column**

In [193]:
df2['product_color'].value_counts()

1     219
2     173
7      77
0      69
16     68
     ...
62      1
64      1
41      1
66      1
65      1
Name: product_color, Length: 88, dtype: int64

In [194]:
#since factorize function turns nan values to -1 we will replace -1 with a value of our own 89
df2['product_color']=df2['product_color'].replace(-1,89)
#replace low frequency values

replace_less_values('product_color',89)

df2['product_color'].value_counts()

1     219
2     173
89    106
7      77
0      69
16     68
8      61
10     61
21     48
26     37
18     22
6      19
9      18
30     16
14     14
11     10
19      8
13      8
34      6
20      6
22      6
5       5
54      5
29      5
37      4
55      4
15      4
31      3
27      3
47      3
50      3
12      3
Name: product_color, dtype: int64

**2-has_urgency_banner**

In [195]:
df2['has_urgency_banner']=df2['has_urgency_banner'].fillna(0)
df2['has_urgency_banner'].value_counts()

0.0    745
1.0    349
Name: has_urgency_banner, dtype: int64

**3-Origin country**

In [196]:
df2['origin_country'].value_counts()

 0    1054
 1      22
-1      12
 4       3
 3       2
 2       1
Name: origin_country, dtype: int64

In [197]:
df2['origin_country']=df2['origin_country'].replace(-1,5)
#replace low frequency values

replace_less_values('origin_country',5)

df2['origin_country'].value_counts()

0    1054
1      22
5      15
4       3
Name: origin_country, dtype: int64

In [198]:
df2.isnull().sum()

price                           0
retail_price                    0
units_sold                      0
uses_ad_boosts                  0
rating                          0
rating_count                    0
badges_count                    0
badge_local_product             0
badge_product_quality           0
badge_fast_shipping             0
product_color                   0
product_variation_size_id       0
product_variation_inventory     0
shipping_option_name            0
shipping_option_price           0
shipping_is_express             0
countries_shipped_to            0
inventory_total                 0
has_urgency_banner              0
origin_country                  0
merchant_rating_count           0
merchant_rating                 0
merchant_has_profile_picture    0
dtype: int64

#Hyper Parameter tuning and model training

In [199]:
X_train=df2.drop(['rating'],axis=1)
y_train=df2['rating']
#First model: Decision tree using grid search to tune hyperparameters
DT_param_1 = {
    'max_depth': [2, 3, 5, 10, 20],
    'min_samples_leaf': [5, 10, 20, 50, 100],
    'min_samples_split':[2,3,4,5],
    'criterion': ["entropy", "gini"]
}

model_dt_1 = DecisionTreeClassifier()


grid_search = GridSearchCV(estimator=model_dt_1, param_grid= DT_param_1, cv=5, n_jobs=-1, verbose=3)


grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 200 candidates, totalling 1000 fits

/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['entropy', 'gini'],
                         'max_depth': [2, 3, 5, 10, 20],
                         'min_samples_leaf': [5, 10, 20, 50, 100],
                         'min_samples_split': [2, 3, 4, 5]},
             verbose=3)

In [200]:
print(grid_search.best_score_)

0.7650831552930335

#this time preprocess the test data and predict

In [201]:
df_test= pd.read_csv('test_new.csv')
df3= df_test.drop(columns=['theme','urgency_text','merchant_title','merchant_info_subtitle','currency_buyer','merchant_name','merchant_id','merchant_profile_picture','crawl_month','tags'])
df3.set_index('id',inplace=True)
def replace_less_values2(col,value_to_be_replaced):
    #extract values with count 2 or less than 2
    bool_lst = [df3[col].value_counts() <= 2]
    lst = list(df3[col].value_counts().index[tuple(bool_lst)])
    #replace them with value of my choice
    df3[col].replace(dict.fromkeys(lst, value_to_be_replaced),inplace=True)

#min_max_scaler constructor
min_max_scaler = MinMaxScaler()
#extract integer columns
myCols = df3.select_dtypes(include='int64').columns
#normlize integer columns
df3[myCols] = min_max_scaler.fit_transform(df3[myCols])
#normalize float columns
df3[['price','merchant_rating']] = min_max_scaler.fit_transform(df3[['price','merchant_rating']])


#Count of product_variation_size_id before the cleaning.
df3['product_variation_size_id'] = df3['product_variation_size_id'].str.upper()
df3.product_variation_size_id = df3.product_variation_size_id.apply(clean_product_size)
replace_less_values2('product_variation_size_id','ANOTHER_SIZE')
#Count of product_variation_size_id after the cleaning.

#identify all categorical variables
cat_columns = df3.select_dtypes(['object']).columns

#convert all categorical variables to numeric
df3[cat_columns] = df3[cat_columns].apply(lambda x: pd.factorize(x)[0])

df3['product_color']=df3['product_color'].replace(-1,89)
#replace low frequency values

replace_less_values2('product_color',89)



df3['has_urgency_banner']=df3['has_urgency_banner'].fillna(0)


df3['origin_country']=df3['origin_country'].replace(-1,5)
#replace low frequency values

replace_less_values2('origin_country',5)
df3.isnull().sum()

price                           0
retail_price                    0
units_sold                      0
uses_ad_boosts                  0
rating_count                    0
badges_count                    0
badge_local_product             0
badge_product_quality           0
badge_fast_shipping             0
product_color                   0
product_variation_size_id       0
product_variation_inventory     0
shipping_option_name            0
shipping_option_price           0
shipping_is_express             0
countries_shipped_to            0
inventory_total                 0
has_urgency_banner              0
origin_country                  0
merchant_rating_count           0
merchant_rating                 0
merchant_has_profile_picture    0
dtype: int64

Prediction and saving file

In [202]:
id=df_test['id']
predicted_test_dt = grid_search.predict(df3)
print(f"best hyperparameters found are {grid_search.best_estimator_}")

predicted_test_dt.astype(float)
prediction=pd.DataFrame()
prediction['id']=id
prediction['rating']=predicted_test_dt

prediction.to_csv('ypred',index=False)

best hyperparameters found are DecisionTreeClassifier(max_depth=3, min_samples_leaf=5)